import * as vscode from "vscode";
import * as fs from "fs/promises";
import * as path from "path";
import { callLlm, type LlmConfig } from "../driver/llmClient";
import { extractFirstBody, parseFrontmatter } from "../util/frontmatter";

const WIKI_REL = path.join("library", "knowledge-base", "wiki");

const BRIEF_SYSTEM =
  "You are an onboarding expert for software engineering teams. Given a list of wiki entity pages, write a concise introductory paragraph (2-3 sentences) that tells a new developer what this area of the codebase does and why it matters.";

/**
 * Generate an ordered onboarding reading guide from wiki entity pages.
 * Entities are sorted foundational-first (highest in-degree = most depended upon).
 */
export async function generateOnboardingBrief(
  repoRoot: string,
  _context: vscode.ExtensionContext
): Promise<void> {
  if (!repoRoot) {
    vscode.window.showErrorMessage("Legion: Open a folder first.");
    return;
  }

  const topic = await vscode.window.showInputBox({
    prompt: "Onboarding topic — module name, feature area, or role",
    placeHolder: "e.g. payments, authentication, react-components",
    validateInput: (v) => (v.trim() ? undefined : "Topic is required"),
  });
  if (!topic) return;

  const cfg = vscode.workspace.getConfiguration("legion");
  const llmConfig = buildLlmConfig(cfg);
  const hasLlm =
    (cfg.get<string>("apiProvider", "anthropic") === "openrouter" && llmConfig.openRouterApiKey) ||
    llmConfig.anthropicApiKey;

  await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `Legion: Generating onboarding brief for "${topic}"…`,
      cancellable: false,
    },
    async (progress) => {
      progress.report({ message: "Loading entity pages…", increment: 20 });

      const wikiRoot = path.join(repoRoot, WIKI_REL);
      const entityDir = path.join(wikiRoot, "entities");

      // Load all entity pages and filter by topic keyword
      const pages = await loadEntityPages(entityDir, topic);
      if (pages.length === 0) {
        vscode.window.showInformationMessage(
          `Legion: No entity pages found for "${topic}". Run Document Repository first.`
        );
        return;
      }

      progress.report({ message: `Sorting ${pages.length} entities foundational-first…`, increment: 20 });

      // Sort by in-degree descending (most depended upon = foundational)
      const sorted = sortByInDegree(pages);

      progress.report({ message: "Writing brief…", increment: 20 });

      // Generate intro paragraph (LLM if available, otherwise skip)
      let intro = `This guide covers the **${topic}** area of the codebase. Read the entities below in order, starting with the most foundational.`;
      if (hasLlm) {
        const entityNames = sorted.slice(0, 10).map((p) => p.name).join(", ");
        try {
          intro = await callLlm(
            llmConfig,
            BRIEF_SYSTEM,
            `Topic: ${topic}\nEntities: ${entityNames}\n\nWrite the intro paragraph.`
          );
        } catch {
          // Fall back to default intro
        }
      }

      progress.report({ message: "Filing onboarding page…", increment: 20 });

      const dateStr = new Date().toISOString().slice(0, 10);
      const slug = topic.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
      const pagePath = path.join(wikiRoot, "meta", `onboarding-${slug}.md`);

      const readingList = sorted
        .slice(0, 20)
        .map((p, i) => {
          const desc = p.firstBody || p.type || "entity";
          return `${i + 1}. [[entities/${p.name}]] — ${desc}`;
        })
        .join("\n");

      const content = [
        `---`,
        `type: meta`,
        `title: "Onboarding: ${topic}"`,
        `topic: "${topic}"`,
        `entity_count: ${sorted.length}`,
        `created: "${dateStr}"`,
        `tags: [onboarding, meta]`,
        `---`,
        ``,
        `# Onboarding Guide — ${topic}`,
        ``,
        intro,
        ``,
        `## Read in this order`,
        ``,
        readingList,
        sorted.length > 20 ? `\n_(${sorted.length - 20} additional entities not shown — run Legion: Find Entity to explore further)_` : "",
        ``,
        `---`,
        ``,
        `*Generated by Legion on ${dateStr}. Run "Legion: Update Documentation" to refresh.*`,
      ]
        .filter((l) => l !== "")
        .join("\n");

      await fs.mkdir(path.dirname(pagePath), { recursive: true });
      await fs.writeFile(pagePath, content);

      // Copy path to clipboard
      await vscode.env.clipboard.writeText(pagePath);

      // Open in side column
      const doc = await vscode.workspace.openTextDocument(pagePath);
      await vscode.window.showTextDocument(doc, vscode.ViewColumn.Beside);
      vscode.window.showInformationMessage(
        `Legion: Onboarding brief filed — path copied to clipboard.`
      );
    }
  );
}

// ── Entity loading + sorting ──────────────────────────────────────────────────

interface EntityPage {
  name: string;
  type: string;
  module: string;
  dependsOn: string[];
  firstBody: string;
}

async function loadEntityPages(entityDir: string, topicFilter: string): Promise<EntityPage[]> {
  let files: string[];
  try {
    files = await fs.readdir(entityDir);
  } catch {
    return [];
  }

  const lowerTopic = topicFilter.toLowerCase();
  const pages: EntityPage[] = [];

  for (const file of files) {
    if (!file.endsWith(".md") || file.startsWith("_")) continue;
    try {
      const content = await fs.readFile(path.join(entityDir, file), "utf8");
      const fm = parseFrontmatter(content);
      const name = file.replace(/\.md$/, "");
      const module = (fm["path"] ?? "").split("/")[0] ?? "";

      // Filter by topic keyword (match name, module, or tags)
      const matchText = `${name} ${module} ${fm["tags"] ?? ""}`.toLowerCase();
      if (!matchText.includes(lowerTopic) && !topicFilter.includes(module)) continue;

      const dependsRaw = fm["depends_on"] ?? "";
      const dependsOn = (dependsRaw.match(/\[\[([^\]|#]+?)(?:[|#][^\]]*?)?\]\]/g) ?? [])
        .map((m) => m.replace(/^\[\[|\]\]$/g, "").split("/").pop()?.replace(/\.md$/, "") ?? "");

      pages.push({
        name,
        type: fm["entity_type"] ?? fm["type"] ?? "entity",
        module,
        dependsOn,
        firstBody: extractFirstBody(content),
      });
    } catch {}
  }

  return pages;
}

function sortByInDegree(pages: EntityPage[]): EntityPage[] {
  const inDegree = new Map<string, number>();
  for (const p of pages) {
    for (const dep of p.dependsOn) {
      if (pages.some((x) => x.name === dep)) {
        inDegree.set(dep, (inDegree.get(dep) ?? 0) + 1);
      }
    }
  }
  return [...pages].sort((a, b) => (inDegree.get(b.name) ?? 0) - (inDegree.get(a.name) ?? 0));
}

function buildLlmConfig(cfg: vscode.WorkspaceConfiguration): LlmConfig {
  const provider = cfg.get<"anthropic" | "openrouter">("apiProvider", "anthropic");
  return {
    provider,
    anthropicApiKey: cfg.get<string>("anthropicApiKey") || process.env.LEGION_ANTHROPIC_API_KEY || "",
    openRouterApiKey: cfg.get<string>("openRouterApiKey") || process.env.LEGION_OPENROUTER_API_KEY || "",
    model: provider === "openrouter"
      ? (cfg.get<string>("openRouterModel") || "anthropic/claude-sonnet-4-5")
      : (cfg.get<string>("model") || "claude-sonnet-4-5"),
    maxTokens: 512,
  };
}
